# Generated by Django 2.0.1 on 2019-08-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('collect_alias', models.CharField(max_length=100, null=True)),
                ('connect_name', models.CharField(max_length=100, null=True)),
                ('sql_text', models.CharField(max_length=4000, null=True)),
                ('create_time', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='databaselist',
            name='dbname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
