# Generated by Django 2.0.1 on 2019-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190819_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='workflow_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(max_length=20, null=True)),
                ('work_id', models.CharField(max_length=20, null=True)),
                ('workflow_name', models.CharField(max_length=50, null=True)),
                ('step_num', models.SmallIntegerField(null=True)),
                ('step_name', models.CharField(max_length=100, null=True)),
                ('handler_user', models.CharField(max_length=20, null=True)),
                ('handler_result', models.CharField(max_length=20, null=True)),
                ('opinion', models.CharField(max_length=4000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='databaselist',
            name='can_search',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='databaselist',
            name='dbrole',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='querypermissions',
            name='connect_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='querypermissions',
            name='create_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_collect',
            name='sort_flag',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='user_collect',
            name='update_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
